server:
  port: 4000
spring:
  profiles:
    active: prod
zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    account-service:
        path: /accounts/**
        service-id: account-service
        strip-prefix: false
        sensitive-headers:

