spring:
  application:
    name: product-service
  profiles:
    active: prod
  data:
    mongodb:
      host: localhost
      database: resto
      port: 27017
      username: root
      password: ahahah
server:
  port: 8082