server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/{application}
  profiles:
     active: native
eureka:
  client:
    registry-fetch-interval-seconds: 5
    region: default
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
